config/routes.rb
Rails.application.routes.draw do

  root to: "api/v1/products#index"

  namespace :api do
    namespace :v1 do
      resources :products do
        resources :comments, only: [:create, :index]
      end
      resources :users, only: [:create] do
        collection do
          get :get_current_user
        end
      end
      post '/signin', to: 'sessions#create'
      delete '/signout', to: 'sessions#destroy', as: 'session'
    end
  end

  get '*path', to: 'api/v1/products#index'
  

  #get 'users/new', to: 'users#new', as: 'new_user'


  # get '/products', to: 'products#index'
  # get '/products/new', to: 'products#new', as: 'new_product'
  # get "/products/:id", to: 'products#show', as: "product"
  # post '/products', to: 'products#create'
  # get '/products/:id/edit', to: 'products#edit', as: 'edit_product'
  # patch '/products/:id', to: 'products#update'
  # delete '/products/:id', to: 'products#destroy'



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
    <h5 class="card-title">
        <%= pluralize(object.errors.count, "error") %>
        prohibited this <%= object.class.name.humanize.downcase %> from being saved.
    </h5>
    <ul>
        <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="text-center">
  Copyright &copy;2020 Eric Brady
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light ">
      <%= link_to "E-Sale", root_path, class: "navbar-brand goog" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to root_path, class: "nav-link" do %>
              Home <span class="sr-only">(current)</span>
            <% end %>
          </li>

          <% unless current_user %>
            <li class="nav-item">
              <%= link_to "Sign In", signin_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Up", signup_path, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "New Product", new_product_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Out", session_path, method: :delete, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <p class="navbar-text">Signed in as <%= current_user.email %></p>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

app/views/shared/_messages.html.erb
<% if flash[:notice] %>
    <div class='alert alert-success text-center' role='alert'>
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class='alert alert-danger text-center' role='alert'>
        <%= flash[:alert] %>
    </div>
<% end %>